name: Vitest Tests
on:
  push:
    branches: [ tests-wip ]
  pull_request:
    branches: [ tests-wip ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm ci
    - name: Run unit tests
      run: npm run test:unit
